In [1]:
import pandas as pd
df = pd.read_csv("supermart.csv")

In [3]:
#Inspect dataset that I downloaded from kaggle
df.head()

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45,Tamil Nadu

In [4]:
df.shape

(9994, 11)

In [5]:
df.columns

Index(['Order ID', 'Customer Name', 'Category', 'Sub Category', 'City',
       'Order Date', 'Region', 'Sales', 'Discount', 'Profit', 'State'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Customer Name  9994 non-null   object
 2   Category       9994 non-null   object
 3   Sub Category   9994 non-null   object
 4   City           9994 non-null   object
 5   Order Date     9994 non-null   object
 6   Region         9994 non-null   object
 7   Sales          9994 non-null   int64
 8   Discount       9994 non-null   float64
 9   Profit         9994 non-null   float64
 10  State          9994 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 859.0+ KB

In [7]:
df.describe()

             Sales     Discount       Profit
count  9994.000000  9994.000000  9994.000000
mean   1496.596158     0.226817   374.937082
std     577.559036     0.074636   239.932881
min     500.000000     0.100000    25.250000
25%    1000.000000     0.160000   180.022500
50%    1498.000000     0.230000   320.780000
75%    1994.750000     0.290000   525.627500
max    2500.000000     0.350000  1120.950000

In [12]:
#Regional Performance
#Which regions generate the most sales and profit?
df.groupby('Region', as_index=False).agg(
    total_sale = ('Sales','sum'),
    total_profit = ('Profit','sum'),
    average_sale = ('Sales','mean'),
    average_profit = ('Profit','mean'),
    number_of_order = ('Order ID','count')
).sort_values(by='total_profit',ascending=False)

,Region,total_sale,total_profit,average_sale,average_profit,number_of_order
4,West,4798743,1192004.61,1498.202623,372.152548,3203
1,East,4248368,1074345.58,1491.702247,377.228083,2848
0,Central,3468156,856806.84,1492.964270,368.836350,2323
3,South,2440461,623562.89,1507.387894,385.153113,1619
2,North,1254,401.28,1254.000000,401.280000,1

In [15]:
#Category Performance
#Which product categories are driving sales and profit?
df.groupby('Category', as_index=False).agg(
    total_sale = ('Sales','sum'),
    total_profit = ('Profit','sum'),
    average_discount = ('Discount','mean'),
    number_of_order = ('Order ID','count')
).sort_values(by='total_profit', ascending=False)

,Category,total_sale,total_profit,average_discount,number_of_order
6,Snacks,2237546,568178.85,0.222048,1514
2,"Eggs, Meat & Fish",2267401,567357.22,0.227792,1490
4,Fruits & Veggies,2100727,530400.38,0.229295,1418
3,Food Grains,2115272,529162.64,0.228548,1398
0,Bakery,2112281,528521.06,0.225428,1413
1,Beverages,2085313,525605.76,0.230329,1400
5,Oil & Masala,2038442,497895.29,0.224526,1361

In [26]:
#High-Value Orders
#Let's define a high-value order as: Sales >= 1500
#Among high-value orders, which categories generate the most sales and profit?
high_value_orders = df.loc[df['Sales'] >= 1500].groupby('Category').agg(
    total_sale = ('Sales','sum'),
    total_profit = ('Profit','sum')
).sort_values(by='total_sale', ascending=False)
high_value_orders

                   total_sale  total_profit
Category
Eggs, Meat & Fish     1532727     384071.80
Snacks                1448470     367291.11
Food Grains           1430988     363179.09
Bakery                1415605     352556.95
Beverages             1413762     357263.64
Oil & Masala          1360421     332923.27
Fruits & Veggies      1359999     345968.91

In [28]:
#Final Analyst Challenge
#I want to know which sub-categories are performing particularly well in the West region. Show me the top-performing sub-categories based on profit.
df.loc[df['Region'] == 'West'].groupby('Sub Category')['Profit'].sum().head(1)

Sub Category
Atta & Flour    40715.33
Name: Profit, dtype: float64

In [ ]:
#RESULT
I found that West Region generate most benefit and sales. it has the most number of order too.
I found Snacks make the most profit with the most number of orders. whereas it has the least discount.
I found amoung high_value orders, Eggs, Meat & Fish make the most profit and sale.
I found Atta & Flour sub category in the west region make the most profit.