agg() = Perform several aggregation operations and give the results together.

In [3]:
#Create Dataset
import pandas as pd

sales = pd.DataFrame({
    "order_id": range(1001, 1013),
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Monitor", "Keyboard"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara", "Ali", "Neda"
    ],
    "region": [
        "North", "South", "West", "East",
        "North", "East", "South", "West",
        "North", "South", "East", "West"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12, 4, 6],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25, 400, 50]
})

sales["revenue"] = sales["quantity"] * sales["price"]

In [4]:
#first example
sales['revenue'].agg(['sum','min','median','max'])

sum       10475.0
min         250.0
median      600.0
max        2000.0
Name: revenue, dtype: float64

In [7]:
#use agg with multiple columns
sales.agg({
    'revenue' : ['sum','min','max'],
    'quantity' : ['sum']
})

     revenue  quantity
sum    10475      70.0
min      250       NaN
max     2000       NaN

PATTERN:
df.agg({
    "column_1": ["function1", "function2"],
    "column_2": ["function3", "function4"]
})

In [9]:
#Named Aggregation
#WHEN WE USE GROUPBY IT CAN BE SO HELPFUL
sales.groupby('product', as_index=False).agg(
    total_revenue=("revenue", "sum"),
    average_revenue=("revenue", "mean"),
    maximum_revenue=("revenue", "max"),
    minimum_revenue=("revenue", "min"),
    total_quantity=("quantity", "sum"),
    number_of_orders=("order_id", "count")
)

,product,total_revenue,average_revenue,maximum_revenue,minimum_revenue,total_quantity,number_of_orders
0,Keyboard,950,316.666667,400,250,19,3
1,Laptop,5000,1666.666667,2000,1000,5,3
2,Monitor,3600,1200.000000,1600,800,9,3
3,Mouse,925,308.333333,375,250,37,3

In [10]:
#agg() + multiple-column groupby()
#Give me a detailed revenue report for every region and product.
sales.groupby(['region','product'],as_index=False).agg(
    total_revenue = ("revenue","sum"),
    average_revenue = ("revenue","mean"),
    maximum_revenue = ("revenue","max"),
    minimum_revenue = ("revenue","min"),
    total_quantity = ("revenue","sum"),
    number_of_order = ("order_id","count")
)

,region,product,total_revenue,average_revenue,maximum_revenue,minimum_revenue,total_quantity,number_of_order
0,East,Laptop,1000,1000.0,1000,1000,1000,1
1,East,Monitor,1600,1600.0,1600,1600,1600,1
2,East,Mouse,375,375.0,375,375,375,1
3,North,Laptop,4000,2000.0,2000,2000,4000,2
4,North,Monitor,1200,1200.0,1200,1200,1200,1
5,South,Keyboard,400,400.0,400,400,400,1
6,South,Mouse,550,275.0,300,250,550,2
7,West,Keyboard,550,275.0,300,250,550,2
8,West,Monitor,800,800.0,800,800,800,1

THERE ARE 2 COMMON STYLE THAT WE CAN USE AGG() :
1- Dictionary aggregation : Good when you want a quick summary.
2- Named aggregation : prefer for analytical reports.

In [12]:
#Mini Analyst Challenge
#Salesperson report
salesperson_report = sales.groupby('salesperson').agg(
    total_revenue = ('revenue','sum'),
    average_order_value = ('revenue','mean'),
    maximum_order_value = ('revenue','max'),
    minimum_order_value = ('revenue','min'),
    total_quantity = ('quantity','sum'),
    number_of_orders = ('order_id','count')
).sort_values(by="total_revenue", ascending=False)

In [13]:
salesperson_report

,total_revenue,average_order_value,maximum_order_value,minimum_order_value,total_quantity,number_of_orders
salesperson,,,,,,
Ali,4225,1056.250000,2000,250,26,4
Reza,3400,1133.333333,2000,400,11,3
Sara,2550,637.500000,1200,250,27,4
Neda,300,300.000000,300,300,6,1

In [18]:
#region_category_report
region_category_report = sales.groupby(['region','category'],as_index=False).agg(
    total_revenue = ('revenue','sum'),
    average_revenue = ('revenue','mean'),
    total_quantity = ('quantity','sum'),
    number_of_orders = ('order_id','count') 
).sort_values(by='total_revenue', ascending=False)

In [19]:
region_category_report

,region,category,total_revenue,average_revenue,total_quantity,number_of_orders
2,North,Electronics,5200,1733.333333,7,3
1,East,Electronics,2600,1300.000000,5,2
3,South,Accessories,950,316.666667,30,3
5,West,Electronics,800,800.000000,2,1
4,West,Accessories,550,275.000000,11,2
0,East,Accessories,375,375.000000,15,1