In [16]:
import pandas as pd
import numpy as np
#Load and audit the dataset
df_raw = pd.read_csv(
    "train.csv"
)

# Work on a copy; preserve the original data
df = df_raw.copy()
# Inspect structure and types
print("Dataset shape:", df.shape)

Dataset shape: (891, 12)

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
print(f"columns name : \n{df.columns}")

columns name :
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
print(f"Summary{df.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
SummaryNone

In [20]:
print(f"Data Types : \n{df.dtypes}")

Data Types :
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [21]:
print(f"Missing Values per columns : \n{df.isna().sum()}")

Missing Values per columns :
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
print(f"Duplicate Rows : \n{df.duplicated().sum()}")

Duplicate Rows :
0

In [22]:
#Create a missing-values report
missing_values_reports = pd.DataFrame({
    'missing_count' : df.isna().sum(),
    'missing_percent' : (df.isna().mean() * 100).round(2)
})
missing_values_reports = missing_values_reports.sort_values(by='missing_count', ascending=False)
missing_values_reports

             missing_count  missing_percent
Cabin                  687            77.10
Age                    177            19.87
Embarked                 2             0.22
PassengerId              0             0.00
Name                     0             0.00
Pclass                   0             0.00
Survived                 0             0.00
Sex                      0             0.00
Parch                    0             0.00
SibSp                    0             0.00
Fare                     0             0.00
Ticket                   0             0.00

In [27]:
#Inspect all occurrences of repeated passengers IDs without assuming they're errors:
df.loc[df.duplicated(subset=['PassengerId'])]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [29]:
#Inspect text values and numeric columns
text_columns = ['Name','Sex', 'Ticket', 'Cabin', 'Embarked']
for col in text_columns:
    print(f'col : {col}')
    print(df[col].value_counts(dropna=False).head(10))
    print()

col : Name
Name
Dooley, Mr. Patrick                                    1
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
Allen, Mr. William Henry                               1
Moran, Mr. James                                       1
McCarthy, Mr. Timothy J                                1
Palsson, Master. Gosta Leonard                         1
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      1
Name: count, dtype: int64

col : Sex
Sex
male      577
female    314
Name: count, dtype: int64

col : Ticket
Ticket
347082          7
1601            7
CA. 2343        7
3101295         6
CA 2144         6
347088          6
382652          5
S.O.C. 14879    5
113760          4
19950           4
Name: count, dtype: int64

col : Cabin
Cabin
NaN            687
G6               4
C23 C25 C27      4
B96 B98          4
F2               3
D                3
E101             3
C22 C26          3
F33              3
C83              2
Name: count, dtype: int64

col : Embarked
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [30]:
#Then inspect numeric summaries:
df[['Survived','Pclass', 'Age']].describe()

         Survived      Pclass         Age
count  891.000000  891.000000  714.000000
mean     0.383838    2.308642   29.699118
std      0.486592    0.836071   14.526497
min      0.000000    1.000000    0.420000
25%      0.000000    2.000000   20.125000
50%      0.000000    3.000000   28.000000
75%      1.000000    3.000000   38.000000
max      1.000000    3.000000   80.000000