In [1]:
import pandas as pd
import numpy as np
#Load and audit the dataset
df_raw = pd.read_csv(
    "MessyFoodPre.csv"
)

# Work on a copy; preserve the original data
df = df_raw.copy()
# Inspect structure and types
print("Dataset shape:", df.shape)

Dataset shape: (911, 12)

In [2]:
df.head()

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category,food_waste_kg
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,intermediate,dairy,28.946465
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,NaN,MeAt,51.549053
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,Beginner,MeAt,53.008323
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,Beginner,MeAt,48.621527
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,Intermediate,MEAT,44.156984

In [3]:
#Perform a data-quality audit
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                911 non-null    int64
 1   date              911 non-null    object
 2   meals_served      911 non-null    int64
 3   kitchen_staff     911 non-null    int64
 4   temperature_C     911 non-null    float64
 5   humidity_percent  911 non-null    float64
 6   day_of_week       911 non-null    int64
 7   special_event     911 non-null    int64
 8   past_waste_kg     911 non-null    float64
 9   staff_experience  747 non-null    object
 10  waste_category    911 non-null    object
 11  food_waste_kg     911 non-null    float64
dtypes: float64(4), int64(5), object(3)
memory usage: 85.5+ KB

In [4]:
print(f'Data types : {df.dtypes}')

Data types : ID                    int64
date                 object
meals_served          int64
kitchen_staff         int64
temperature_C       float64
humidity_percent    float64
day_of_week           int64
special_event         int64
past_waste_kg       float64
staff_experience     object
waste_category       object
food_waste_kg       float64
dtype: object

In [9]:
#Find missing values
missing_report = pd.DataFrame({
    'missing_count' : df.isna().sum(),
    'missing_average' : (df.isna().mean() * 100).round(2)
})
missing_report

                  missing_count  missing_average
ID                            0              0.0
date                          0              0.0
meals_served                  0              0.0
kitchen_staff                 0              0.0
temperature_C                 0              0.0
humidity_percent              0              0.0
day_of_week                   0              0.0
special_event                 0              0.0
past_waste_kg                 0              0.0
staff_experience            164             18.0
waste_category                0              0.0
food_waste_kg                 0              0.0

In [10]:
#Find exact duplicates
print(f'Exact Duplicated : {df.duplicated().sum()}')

Exact Duplicated : 0

In [11]:
#Inspect the duplicates:
duplicated = df.loc[df.duplicated(keep=False)]
duplicated

Empty DataFrame
Columns: [ID, date, meals_served, kitchen_staff, temperature_C, humidity_percent, day_of_week, special_event, past_waste_kg, staff_experience, waste_category, food_waste_kg]
Index: []

In [12]:
#Inspect numerical statistics
df.describe()

,ID,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,food_waste_kg
count,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000,911.000000
mean,528.327113,375.405049,11.900110,22.189280,60.761313,3.014270,0.085620,27.015691,44.842691
std,305.072794,502.812717,4.285153,8.922389,17.330821,2.009542,0.279956,12.774223,27.934366
min,0.000000,100.000000,5.000000,-10.372207,30.121111,0.000000,0.000000,5.008394,10.819048
25%,266.000000,211.000000,8.000000,15.684585,46.017835,1.000000,0.000000,16.091383,32.887912
50%,531.000000,306.000000,12.000000,22.115040,61.633960,3.000000,0.000000,26.854109,41.146930
75%,795.500000,407.000000,15.000000,28.804294,75.787910,5.000000,0.000000,38.149878,50.046681
max,1049.000000,4730.000000,19.000000,60.000000,89.982828,6.000000,1.000000,49.803703,274.328783

In [13]:
#Clean text columns
df['staff_experience'] = (
    df['staff_experience']
    .str.strip()
    .str.lower()
)
df.head()

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category,food_waste_kg
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,intermediate,dairy,28.946465
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,NaN,MeAt,51.549053
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,beginner,MeAt,53.008323
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,beginner,MeAt,48.621527
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,intermediate,MEAT,44.156984

In [14]:
#Inspect the original categories
print(df['waste_category'].value_counts(dropna=False))

waste_category
MEAT          210
dairy         180
Vegetables    176
GRAINS        176
MeAt          169
Name: count, dtype: int64

In [15]:
#Standardise the categories
df['waste_category'] = (
    df['waste_category']
    .str.strip()
    .str.lower()
)
print(df['waste_category'].value_counts(dropna=False))

waste_category
meat          379
dairy         180
vegetables    176
grains        176
Name: count, dtype: int64

In [17]:
#Investigate missing values
print(df['staff_experience'].value_counts(dropna=False))

staff_experience
intermediate    370
beginner        191
expert          186
NaN             164
Name: count, dtype: int64

In [22]:
#Compare missing and non-missing rows
print(f'Missinga :')
display(df.loc[df['staff_experience'].isna()].head(10))
print(f'Not Missinga : ')
display(df.loc[df['staff_experience'].notna()].head(10))

Missinga :

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category,food_waste_kg
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,NaN,meat,51.549053
14,17,2023-04-29,378,12,12.323229,68.060384,5,0,41.146021,NaN,meat,51.058018
19,22,2024-09-09,253,17,12.768711,42.373044,0,0,6.584683,NaN,dairy,18.665798
31,34,2022-04-12,114,8,24.756598,38.251426,1,0,25.343897,NaN,meat,23.016292
38,41,2024-01-01,272,11,16.947552,32.858475,0,0,30.910364,NaN,meat,39.502640
46,49,2024-07-07,487,6,24.004556,56.945085,6,0,25.590890,NaN,grains,44.274850
52,55,2023-09-09,385,15,33.570779,57.515877,5,0,8.089190,NaN,meat,31.256636
53,56,2022-02-19,373,10,21.713485,88.366579,5,0,34.335539,NaN,dairy,53.953181
58,62,2023-05-13,188,19,22.743106,54.947850,5,0,35.449009,NaN,vegetables,42.653946
71,78,2022-01-20,357,13,10.481220,81.983191,3,0,26.440757,NaN,vegetables,45.211063

Not Missinga :

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category,food_waste_kg
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,intermediate,dairy,28.946465
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,beginner,meat,53.008323
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,beginner,meat,48.621527
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,intermediate,meat,44.156984
5,7,2023-03-02,241,18,16.863506,79.285919,3,0,11.834878,intermediate,dairy,27.393670
6,8,2022-04-18,443,16,19.888627,77.328136,0,0,22.862659,beginner,vegetables,52.172118
7,9,2023-12-16,416,16,18.559591,75.786502,5,1,34.599442,intermediate,meat,72.052407
8,10,2023-07-07,439,18,24.111027,43.395803,4,0,17.459149,expert,dairy,44.284157
9,11,2023-11-07,267,7,25.412493,89.405183,1,0,23.067392,expert,grains,33.233930
10,12,2022-06-08,487,15,20.965180,53.392341,2,0,41.075793,expert,meat,61.213326

In [23]:
#Decide how to handle missing experience
df['staff_experience'] = (
    df['staff_experience']
    .fillna('Unknown')
)

In [24]:
df.isna().sum()

ID                  0
date                0
meals_served        0
kitchen_staff       0
temperature_C       0
humidity_percent    0
day_of_week         0
special_event       0
past_waste_kg       0
staff_experience    0
waste_category      0
food_waste_kg       0
dtype: int64

In [25]:
#Fix data types and dates
df['date'] = pd.to_datetime(
    df['date'],
    errors='coerce'
)
df.dtypes

ID                           int64
date                datetime64[ns]
meals_served                 int64
kitchen_staff                int64
temperature_C              float64
humidity_percent           float64
day_of_week                  int64
special_event                int64
past_waste_kg              float64
staff_experience            object
waste_category              object
food_waste_kg              float64
dtype: object

In [27]:
#Investigate numeric anomalies
print(f'Temperate That is not True logicaly : ')
df.loc[(df['temperature_C']<0) | (df['temperature_C']>40)]

Temperate That is not True logicaly :

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category,food_waste_kg
12,15,2022-01-25,376,19,-10.372207,54.498381,1,0,36.259420,expert,meat,50.568699
102,115,2024-02-24,134,6,-10.000000,37.796482,5,0,49.359571,beginner,meat,36.163483
238,279,2023-03-06,453,5,-10.000000,57.790363,0,1,48.434434,intermediate,vegetables,71.752271
290,337,2022-08-28,259,9,60.000000,52.734617,6,0,49.281418,beginner,meat,44.955417
300,350,2023-03-07,421,18,60.000000,44.079207,1,0,24.268277,intermediate,meat,33.139494
345,401,2024-02-01,472,7,-10.000000,79.081605,3,0,27.590369,expert,vegetables,46.991245
384,450,2022-03-15,359,10,-10.000000,82.634367,1,0,47.370958,intermediate,meat,70.472339
396,464,2023-02-27,420,5,60.000000,73.187487,0,0,21.827621,beginner,meat,40.893641
404,474,2023-04-14,469,12,60.000000,32.537505,4,0,35.121064,Unknown,meat,67.151136
407,477,2022-01-25,376,19,-10.000000,54.498381,1,0,36.259420,expert,meat,50.568699
445,521,2023-01-29,459,16,-10.000000,64.622440,6,0,30.083223,beginner,meat,60.690374
463,539,2023-07-30,341,9,-10.000000,44.349527,6,0,36.750322,expert,meat,47.533061
492,571,2022-04-04,152,14,-10.000000,82.113090,0,0,8.452527,intermediate,grains,30.175709
537,621,2022-12-20,383,14,60.000000,31.847403,1,0,6.391890,expert,dairy,35.352474
560,645,2023-09-18,286,15,60.000000,53.511498,0,0,21.347276,expert,dairy,34.982513
641,747,2024-02-04,447,12,60.000000,37.521389,6,0,7.453037,intermediate,meat,37.225888
701,815,2022-09-25,247,19,-10.000000,52.223819,6,1,12.627684,beginner,dairy,42.581728
710,825,2023-01-09,379,15,-10.000000,30.139053,0,0,22.312966,beginner,dairy,45.178594
766,887,2023-04-06,471,6,60.000000,64.308550,3,1,44.209186,expert,grains,64.037547
768,889,2024-05-07,335,15,-10.000000,82.679070,1,0,38.660723,beginner,meat,52.082864
804,933,2022-05-19,356,13,60.000000,80.635477,3,0,44.147202,intermediate,meat,50.385559
852,987,2024-07-20,150,14,-10.000000,86.379091,5,1,23.103817,intermediate,vegetables,47.439001